# Generated by Django 3.1.1 on 2020-10-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200926_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dimensions',
            field=models.CharField(default='kielbasa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Kielbasa', max_length=50),
            preserve_default=False,
        ),
    ]
