# Generated by Django 3.1.1 on 2020-10-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201002_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
    ]
