# Generated by Django 3.1.1 on 2020-10-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='aparatment_numer',
            new_name='apartment_numer',
        ),
    ]
